#!/bin/sh -e

# Programmatically generate CLI documentation from
# Pyjuter's own help dialogs.

code_block () {
    echo '```'
    cat
    echo '```'
}

command_summary () {
    echo "\$ $1" | code_block
    $1 | code_block
    echo
}

cat << EOF
# Command-Line Interface to Pyjuter
Programmatically generated by
generate-cmdline-usage.sh

EOF


echo '## Summary'
command_summary 'python3 -m pyjuter -h'

echo "## Subcommands"
for cmd in p2j j2p; do
    echo "### $cmd"
    command_summary "python3 -m pyjuter $cmd -h"
done
