name: CI

on:
  push:
    branches: [ "master", "ci", "ci-*" ]

  workflow_dispatch:

permissions:
  id-token: write  # Reference: [1]
  pages: write

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ci

    steps:
      - uses: actions/checkout@v4

      - name: Set up CI
        run: |
          ./ci.sh setup

      - name: Tests
        run: ./ci.sh tests

      - name: Static Type-Checking
        run: ./ci.sh typecheck

      - name: Generate docs
        run: |
          ./ci.sh docs

      - name: Upload docs artifact
        id: docs
        uses: actions/upload-pages-artifact@v3
        with:
          path: ci/site/

      # TODO[ci]: integrate with PyPI?
      #- name: Build Package
      #  run: ./ci.sh package

  # Deploy the artifact from `ci` to Pages, only if this
  # branch is `ci`.
  deploy:
    needs: ci
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/ci' }}  # Reference: [2]
    steps:
      - name: Deploy docs
        id: docs
        uses: actions/deploy-pages@v4

# References:
# 1. https://github.com/actions/deploy-pages?tab=readme-ov-file#security-considerations
# 2. https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs
